;; Standard error constants
(define-constant ERR_UNAUTHORIZED (err u100))
(define-constant ERR_INVALID_AMOUNT (err u101))
(define-constant ERR_NOT_FOUND (err u102))
(define-constant ERR_ALREADY_EXISTS (err u103))
(define-constant ERR_PAUSED (err u104))
(define-constant ERR_INVALID_INPUT (err u105))
(define-constant ERR_POOL_NOT_FOUND (err u1000))
(define-constant ERR_POOL_ALREADY_EXISTS (err u1001))
(define-constant ERR_INSUFFICIENT_LIQUIDITY (err u1002))
(define-constant ERR_SLIPPAGE_TOO_HIGH (err u1003))
(define-constant ERR_INVALID_TOKEN_PAIR (err u1004))
(define-constant err-invalid-pool-type (err u1500))
(define-constant err-pool-already-exists (err u1501))
(define-constant err-asset-not-found (err u1502))
(define-constant err-circuit-open (err u1503))
(define-constant err-commit-exists (err u1600))
(define-constant err-commit-not-found (err u1601))
(define-constant err-reveal-window-closed (err u1602))
(define-constant err-reveal-window-open (err u1603))
(define-constant err-invalid-order-hash (err u1604))
(define-constant err-auction-not-active (err u1605))
(define-constant err-auction-active (err u1606))
(define-constant err-bid-window-closed (err u1607))
(define-constant ERR_DIMENSION_NOT_CONFIGURED (err u2000))
(define-constant ERR_POSITION_NOT_FOUND (err u2001))
(define-constant ERR_INVALID_LEVERAGE (err u2002))
(define-constant ERR_MARGIN_CALL (err u2003))
(define-constant ERR_POSITION_CLOSED (err u2004))
(define-constant ERR_ORACLE_FAILURE (err u3000))
(define-constant ERR_STALE_PRICE (err u3001))
(define-constant ERR_INVALID_PRICE_RANGE (err u3002))
(define-constant ERR_NO_STAKE_FOUND (err u4000))
(define-constant ERR_LOCKUP_NOT_EXPIRED (err u4001))
(define-constant ERR_INVALID_LOCK_PERIOD (err u4002))
(define-constant ERR_REWARDS_CLAIMED (err u4003))

;; Getter functions for read-only access
(define-read-only (get-err-unauthorized) ERR_UNAUTHORIZED)
(define-read-only (get-err-invalid-amount) ERR_INVALID_AMOUNT)
(define-read-only (get-err-not-found) ERR_NOT_FOUND)
(define-read-only (get-err-already-exists) ERR_ALREADY_EXISTS)
(define-read-only (get-err-paused) ERR_PAUSED)
(define-read-only (get-err-invalid-input) ERR_INVALID_INPUT)
(define-read-only (get-err-pool-not-found) ERR_POOL_NOT_FOUND)
(define-read-only (get-err-pool-already-exists) ERR_POOL_ALREADY_EXISTS)
(define-read-only (get-err-insufficient-liquidity) ERR_INSUFFICIENT_LIQUIDITY)
(define-read-only (get-err-slippage-too-high) ERR_SLIPPAGE_TOO_HIGH)
(define-read-only (get-err-invalid-token-pair) ERR_INVALID_TOKEN_PAIR)
(define-read-only (get-err-dimension-not-configured) ERR_DIMENSION_NOT_CONFIGURED)
(define-read-only (get-err-position-not-found) ERR_POSITION_NOT_FOUND)
(define-read-only (get-err-invalid-leverage) ERR_INVALID_LEVERAGE)
(define-read-only (get-err-margin-call) ERR_MARGIN_CALL)
(define-read-only (get-err-position-closed) ERR_POSITION_CLOSED)
(define-read-only (get-err-oracle-failure) ERR_ORACLE_FAILURE)
(define-read-only (get-err-stale-price) ERR_STALE_PRICE)
(define-read-only (get-err-invalid-price-range) ERR_INVALID_PRICE_RANGE)

