;; DEPRECATED - Use direct trait references instead
;; (define-constant TRAIT_ACCESS_CONTROL 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.access-control)
;; (define-constant TRAIT_SIP010 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sip-010-trait)
;; (define-constant TRAIT_POOL 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.pool-trait)
;; (define-constant TRAIT_ORACLE 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.oracle-trait)
